sudo: false

language: python
python:
 - 3.5
 - 3.6

install:
      # We do this conditionally because it saves us some downloading if the
      # Miniconda version is the same as the test environment.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - sed -i -e "s/\${TRAVIS_PYTHON_VERSION}/"${TRAVIS_PYTHON_VERSION}"/" test-environment.yaml
    - conda env create -qf test-environment.yaml
    - source activate test-environment
      # Useful for debugging any issues with conda
    - conda info -a
    - conda list

    # just until conda-forge recipes available
    - pip install habanero orcid

# command to run tests
#script: pytest -vv --cov=./ && pylint pyked/
script: pytest -vv --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)
