version: 1.0.{build}
environment:
  ANACONDA_KEY:
    secure: agG4yvYjpYq1nzjLhnZ92Z6ZFVM+KA5JyYIYwX2YVQxpuRj7myqJNfttUVTqynIg

  matrix:
    - PYTHON_LOC: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"

    - PYTHON_LOC: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.5"

    - PYTHON_LOC: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda config --append channels conda-forge
  - cmd: conda update -q conda
  - ps: (get-content test-environment.yaml) | %{$_ -replace "\$\{PYTHON\}",$env:PYTHON_VERSION} | set-content test-environment.yaml
  - cmd: IF "%APPVEYOR_REPO_TAG%"=="false" conda env create -qf test-environment.yaml
  - cmd: IF "%APPVEYOR_REPO_TAG%"=="false" call %PYTHON_LOC%\Scripts\activate.bat test-environment
  - cmd: IF "%APPVEYOR_REPO_TAG%"=="true" conda install -yq anaconda-client conda-build
  - cmd: conda info -a
  - cmd: conda list

build_script:
  - cmd: IF "%APPVEYOR_REPO_TAG%"=="false" python setup.py test
  - cmd: IF "%APPVEYOR_REPO_TAG%"=="true" conda build conda.recipe --python=%PYTHON_VERSION%

deploy_script:
  - cmd: IF "%APPVEYOR_REPO_TAG%"=="true" anaconda -t %ANACONDA_KEY% upload "%PYTHON_LOC%\conda-bld\win-64\pyked*.tar.bz2"
