name: build-env
channels:
- defaults
- conda-forge
dependencies:
  - numpy>=1.11.0
  - pyyaml>=3.12
  - pytest>=3.0.0
  - pytest-cov>=2.3.1
  - python=3.6
  - cerberus>=1.0.0
  - pint>=0.7.2
  - pandas
  - uncertainties
  - habanero
  - orcid
  - sphinx
  - nbsphinx
  - ipython
